{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "paradox.serviceAccountName" . }}
  labels:
    {{- include "paradox.labels" . | nindent 4 }}
{{- end }}
